 - name: Edit IHS Host Table
   lineinfile: dest=/etc/hosts regexp='.*{{item}}$' line='{{hostvars[item].ansible_default_ipv4.address}} {{item}}' state=present
   with_items: '{{groups.ihs}}'
   tags:
     - hosts
