 - name: Edit Admin.conf
   replace:
      dest: "{{IHS_Path}}/conf/admin.conf"
      regexp: localhost
      replace: "{{IHSCFG_Hostname}}"
      owner: "{{IHSUser}}"
      group: "{{IHSGroup}}"
      mode: 0755
